[package]
name = "weather-station"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
dht22_pi = "1.0.0"
eyre = "0.6.8"
home = "0.5.4"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.151", features = ["derive"] }
